train_dataloader:
    batch_size: 16
    shuffle: True
    num_workers: 1

val_dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 1

test_dataloader:
    batch_size: 11
    shuffle: False
    num_workers: 1

model:
    name: 'resnet18'
    n_classes: 3
    pretrained: True

train:
    max_epochs: 3
    gpus: 1