train_dataloader:
    batch_size: 16
    shuffle: True
    num_workers: 1

val_dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 1

test_dataloader:
    batch_size: 11
    shuffle: False
    num_workers: 1

model:
    name: 'resnet18'
    n_classes: 3
    pretrained: True
    lr: 0.0001

train:
    max_epochs: 3
    gpus: 1

infer:
    device: 'cpu'
    path_to_save: 'first_infer'
    path_label_encoder: 'label_encoder.pkl'

path_to_checkpoints: 'lightning_logs\version_0\epoch=2-step=114.ckpt'
